spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fs_prod
    username: fs_prod_user
    password: password
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false